---

- name: Adding primary group
  group:
    name: "{{ users_group }}"
    state: present
  when: users_group is defined and users_group

- name: Adding secondary groups
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ users_groups | default([]) }}"

- name: Select users for the current server
  set_fact:
    users_for_server: "{{ users_for_server | default([]) + [item.0 | combine({'servers':item.1})] }}"
  with_subelements:
    - "{{ users }}"
    - servers
    - flags:
      skip_missing: true
  when: item.1 == inventory_hostname

- name: Select users for all servers
  set_fact:
    users_for_server: "{{ users_for_server | default([]) + [item | combine({'servers':'all'})] }}"
  with_items:
    - "{{ users }}"
  when: item.servers is undefined

- name: Adding user-specific primary group
  group:
    name: "{{ item.group }}"
    state: present
  with_items: "{{ users_for_server | default([]) }}"
  when: item.group is defined and item.group

- name: Adding users
  user:
    name: "{{ item.username }}"
    uid: "{{ item.uid | default(omit) }}"
    home: "{{ item.home | default(users_home ~ '/' ~ item.username ) }}"
    comment: "{{ item.name | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
    generate_ssh_key: "{{ item.ssh_key_generate | default(omit) }}"
    group: "{{ omit if item.group is defined and item.group == item.username else (item.group if item.group is defined else (users_group if users_group else omit)) }}"
    groups: "{{ item.groups|join(',') if item.groups is defined else users_groups|join(',')}}"
    append: "{{ item.append | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    ssh_key_file: ".ssh/id_{{ item.ssh_key_type | default(users_ssh_key_type) }}"
    ssh_key_passphrase: "{{ item.ssh_key_password | default(omit) }}"
    ssh_key_bits: "{{ item.ssh_key_bits | default(users_ssh_key_bits) }}"
    createhome: "{{ item.home_create | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    update_password: "{{ item.update_password | default(omit) }}"
  with_items: "{{ users_for_server | default([]) }}"

- name: Setting user's home permission
  file:
    dest: "{{ item.home | default(users_home ~ '/' ~ item.username) }}"
    owner: "{{ item.username }}"
    group: "{{ item.group if item.group is defined else (users_group if users_group else item.username) }}"
    mode: "{{ item.home_mode if item.home_mode is defined else users_home_mode }}"
  when: item.home_create is not defined or item.home_create
  with_items: "{{ users_for_server | default([]) }}"

- name: Adding user's .ssh directory
  file:
    path: "{{ item.home | default(users_home ~ '/' ~ item.username) }}/.ssh"
    owner: "{{ item.username }}"
    group: "{{ item.group if item.group is defined else (users_group if users_group else item.username) }}"
    state: directory
    mode: '0700'
  when: item.home_create is not defined or item.home_create
  with_items: "{{ users_for_server | default([]) }}"

- name: Adding user's private key
  template:
    src: home-user-ssh-private-key.j2
    dest: "{{ item.home | default(users_home ~ '/' ~ item.username) }}/.ssh/id_{{ item.ssh_key_type | default('rsa') }}"
    owner: "{{ item.username }}"
    group: "{{ item.group if item.group is defined else (users_group if users_group else item.username) }}"
    mode: '0600'
  when: (item.home_create is not defined or item.home_create) and item.ssh_key is defined
  with_items: "{{ users_for_server | default([]) }}"

- name: Adding user's authorized keys
  authorized_key:
    key: "{{ item.authorized_keys | default([]) | join('\n') }}"
    user: "{{ item.username }}"
    path: "{{ item.authorized_keys_path | default(users_authorized_keys_path) | regex_replace('###USERNAME###', item.username) }}"
    manage_dir: "{{ item.authorized_keys_manage_dir | default(users_authorized_keys_manage_dir) }}"
    exclusive: "{{ item.authorized_keys_exclusive | default(users_authorized_keys_exclusive) }}"
  when: item.home_create is not defined or item.home_create or (item.authorized_keys_path is defined and item.authorized_keys_path) or users_authorized_keys_path
  with_items: "{{ users_for_server | default([]) }}"

- name: Removing users
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  with_items: "{{ users_remove }}"
