---

- name: Adding primary group
  ansible.builtin.group:
    name: "{{ users_group }}"
    state: present
  when: users_group is defined and users_group

- name: Adding secondary groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  with_items: "{{ users_groups | default([]) }}"

- name: Select users for the current server
  set_fact:
    users_for_server: "{{ users_for_server | default([]) + [item.0 | combine({'servers':item.1})] }}"
  with_subelements:
    - "{{ users }}"
    - servers
    - flags:
      skip_missing: true
  when: item.1 == inventory_hostname

- name: Select users for all servers
  set_fact:
    users_for_server: "{{ users_for_server | default([]) + [item | combine({'servers':'all'})] }}"
  with_items:
    - "{{ users }}"
  when: item.servers is undefined

- name: Configure users
  include_tasks: manage_user.yml
  with_items: "{{ users_for_server }}"
  loop_control:
    loop_var: user

- name: Removing users
  ansible.builtin.user:
    name: "{{ item.username if item.username is defined else item }}"
    state: absent
    remove: "{{ item.remove if item.remove is defined else omit }}"
  with_items: "{{ users_remove }}"
